apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "elasticsearch.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels: {{ include "elasticsearch.labels" . | nindent 4 }}
data:
  username: {{ default "admin" .Values.auth.username | b64enc | quote }}
  password: {{ default "admin" .Values.auth.password | b64enc | quote }}
type: Opaque
